path:  # dataset root dir
train: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/aakash-rao-capstone-project/datasets/yolov5/fold_3/train/images  
val: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/aakash-rao-capstone-project/datasets/yolov5/fold_3/val/images  
test: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/aakash-rao-capstone-project/datasets/yolov5/test/images
names: 
  0: 'nonTIL_stromal'
  1: 'sTIL'
  2: 'tumor_any'
  3: 'other'
