# Fold 1
path: 
train: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/capstone_project/object-detection/benchmarking/datasets/yolov5_single/fold_3/train/images  
val: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/capstone_project/object-detection/benchmarking/datasets/yolov5_single/fold_3/val/images  
test: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/capstone_project/object-detection/benchmarking/datasets/yolov5_single/test/images 
names: 
  0: 'cell'