# Fold 1
path: /storage/bic/Aakash/aakash-rao-capstone-project/datasets/yolov5
train: fold_1/train/images  
val: fold_1/val/images  
test: test/images 
names: 
  0: 'nonTIL_stromal'
  1: 'sTIL'
  2: 'tumor_any'
  3: 'other'