# Fold 1
train: /storage/bic/Aakash/aakash-rao-capstone-project/datasets/yolov5/fold_2/train/images  
val: /storage/bic/Aakash/aakash-rao-capstone-project/datasets/yolov5/fold_2/val/images  
test: /storage/bic/Aakash/aakash-rao-capstone-project/datasets/yolov5/test/images 
names:  
  0: 'nonTIL_stromal'
  1: 'sTIL'
  2: 'tumor_any'
  3: 'other'